# Generated by Django 5.1.4 on 2025-04-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='inspection',
            field=models.BooleanField(default=True),
        ),
    ]
