# Generated by Django 5.1.4 on 2025-04-30 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_inspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateField(null=True)),
                ('significant', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'InstallationRecord',
                'managed': True,
                'unique_together': {('customer', 'installation_date')},
            },
        ),
        migrations.CreateModel(
            name='InstallationCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.installationrecord')),
            ],
            options={
                'db_table': 'InstallationCert',
                'managed': True,
            },
        ),
    ]
