# Generated by Django 5.1.4 on 2025-04-30 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_installationrecord_installationcert'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationrecord',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.manager', to_field='name'),
        ),
    ]
