# Generated by Django 5.1.4 on 2025-05-08 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_installationrecord_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', to_field='name'),
        ),
    ]
