# Generated by Django 5.1.4 on 2025-05-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_installationrecord_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationrecord',
            name='installation_date',
            field=models.DateField(),
        ),
    ]
