# Generated by Django 5.1.4 on 2025-05-14 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_installationrecord_installation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationcert',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.installationrecord', unique=True),
        ),
    ]
