# Generated by Django 5.1.4 on 2025-05-14 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_installationcert_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationcert',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.installationrecord'),
        ),
    ]
