version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: teamweb_db
    restart: always
    environment:
      POSTGRES_DB: teamweb
      POSTGRES_USER: seteam
      POSTGRES_PASSWORD: 'Qwer123$$'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: teamweb_app
    restart: always
    depends_on:
      - db
    environment:
      - DB_NAME=teamweb
      - DB_USER=seteam
      - DB_PASSWORD='Qwer123$$'
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"