version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: teamweb_db
    restart: always
    env_file: prod.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: teamweb_app
    restart: always
    depends_on:
      - db
    env_file: prod.env
    ports:
      - "8000:8000"
    volumes:
      - report_file:/app/seteamweb/report_save_path

volumes:
  postgres_data:
    driver: local
  report_file:
    driver: local
