version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: teamweb_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/seteamweb
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]