# Generated by Django 5.1.4 on 2025-01-08 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=25)),
                ('license_expire_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', to_field='name')),
            ],
            options={
                'db_table': 'Packages',
                'managed': True,
                'unique_together': {('name', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='iOSApplyOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objc_string_encryption', models.BooleanField(default=False)),
                ('swift_string_encryption', models.BooleanField(default=False)),
                ('jailbreak_check', models.BooleanField(default=False)),
                ('threat_check', models.BooleanField(default=False)),
                ('integrity_check', models.BooleanField(default=False)),
                ('flex_3_check', models.BooleanField(default=False)),
                ('server_auth_manually', models.BooleanField(default=False)),
                ('objc_obfuscate', models.BooleanField(default=False)),
                ('swift_obfuscate', models.BooleanField(default=False)),
                ('symbol_delete', models.BooleanField(default=False)),
                ('log_hiding', models.BooleanField(default=False)),
                ('dynamic_api_hiding', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packages')),
            ],
            options={
                'db_table': 'iOSApplyOptions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AndroidApplyOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_root', models.BooleanField(default=False)),
                ('detect_magisk', models.BooleanField(default=False)),
                ('check_integrity', models.BooleanField(default=False)),
                ('check_emul', models.BooleanField(default=False)),
                ('check_debugging', models.BooleanField(default=False)),
                ('prevent_debugging', models.BooleanField(default=False)),
                ('prevent_adb', models.BooleanField(default=False)),
                ('encrypt_so', models.BooleanField(default=False)),
                ('self_protect', models.BooleanField(default=False)),
                ('prevent_decompile', models.BooleanField(default=False)),
                ('chekc_mem_scanner', models.BooleanField(default=False)),
                ('encrypt_flutter', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packages')),
            ],
            options={
                'db_table': 'AndroidApplyOptions',
                'managed': True,
            },
        ),
    ]
