# Generated by Django 5.1.4 on 2024-12-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='platform',
            field=models.CharField(max_length=25),
        ),
    ]
