# Generated by Django 5.1.4 on 2025-01-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Manager',
                'managed': True,
            },
        ),
    ]
