# Generated by Django 5.1.4 on 2024-12-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
