# Generated by Django 5.1.4 on 2025-01-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidDevices',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('architecture', models.CharField(max_length=20)),
                ('rooting', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'AndroidDevices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='iOSDevices',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('architecture', models.CharField(max_length=20)),
                ('rooting', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'iOSDevices',
                'managed': True,
            },
        ),
    ]
