# Generated by Django 5.1.4 on 2025-01-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devices_delete_androiddevices_delete_iosdevices'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='devices',
            unique_together=set(),
        ),
    ]
