# Generated by Django 5.1.4 on 2025-11-06 13:00

import apps.utils.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Unknown', max_length=30, null=True)),
                ('app_version', models.CharField(default='Unknown', max_length=30, null=True)),
                ('rooting', models.BooleanField(default=False)),
                ('integrity', models.BooleanField(default=False)),
                ('emulator', models.BooleanField(default=False)),
                ('obfuscate', models.TextField(default='Unknown', null=True)),
                ('momo_size', models.TextField(default='Unknown', null=True)),
                ('decompile', models.BooleanField(default=False)),
                ('inspection_month', models.CharField(default='2025-11', max_length=7, validators=[apps.utils.utils.validate_year_month])),
                ('package', models.ForeignKey(limit_choices_to={'platform': 'Android'}, on_delete=django.db.models.deletion.CASCADE, to='packages.packages')),
            ],
            options={
                'db_table': 'AndroidResult',
                'managed': True,
                'unique_together': {('package', 'inspection_month')},
            },
        ),
    ]
