# Generated by Django 5.1.4 on 2026-01-07 01:43

import apps.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidresult',
            name='inspection_month',
            field=models.CharField(default='2026-01', max_length=7, validators=[apps.utils.utils.validate_year_month]),
        ),
    ]
