# Generated by Django 5.1.4 on 2025-01-08 01:23

import apps.utils.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidInspectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_info', models.CharField(blank=True, max_length=30, null=True)),
                ('rooting_test', models.BooleanField(default=False)),
                ('rooting', models.BooleanField(default=False)),
                ('integrity', models.BooleanField(default=False)),
                ('emulator', models.BooleanField(default=False)),
                ('obfuscate', models.BooleanField(default=False)),
                ('decompile', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packages')),
            ],
            options={
                'db_table': 'AndroidInspectResult',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_month', models.CharField(max_length=7, validators=[apps.utils.utils.validate_year_month])),
                ('inspection_date', models.DateField(null=True)),
                ('result', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=15)),
                ('details', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'InspectionRecord',
                'managed': True,
                'unique_together': {('customer', 'inspection_month')},
            },
        ),
        migrations.CreateModel(
            name='InspectionResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspectrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.inspectionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Period', models.CharField(choices=[('monthly', 'Monthly'), ('quarter', 'Quarter'), ('half', 'Half'), ('undecided', 'Undecided')], default='undecided', max_length=25)),
                ('January', models.BooleanField(default=False)),
                ('February', models.BooleanField(default=False)),
                ('March', models.BooleanField(default=False)),
                ('April', models.BooleanField(default=False)),
                ('May', models.BooleanField(default=False)),
                ('June', models.BooleanField(default=False)),
                ('July', models.BooleanField(default=False)),
                ('August', models.BooleanField(default=False)),
                ('September', models.BooleanField(default=False)),
                ('October', models.BooleanField(default=False)),
                ('November', models.BooleanField(default=False)),
                ('December', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', to_field='name')),
            ],
            options={
                'db_table': 'InspectionSchedule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='iOSInspectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_info', models.CharField(blank=True, max_length=30, null=True)),
                ('jailbreak_test', models.BooleanField(default=False)),
                ('jailbreak', models.BooleanField(default=False)),
                ('integrity', models.BooleanField(default=False)),
                ('string_encrypt', models.BooleanField(default=False)),
                ('symbol_del', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packages')),
            ],
            options={
                'db_table': 'iOSInspectResult',
                'managed': True,
            },
        ),
    ]
