# Generated by Django 5.1.4 on 2025-01-16 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_devices_unique_together'),
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iosinspectresult',
            name='library_version',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='androidinspectresult',
            name='device_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devices'),
        ),
        migrations.AlterField(
            model_name='iosinspectresult',
            name='device_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devices'),
        ),
    ]
