# Generated by Django 5.1.4 on 2024-12-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionschedule',
            name='Period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarter', 'Quarter'), ('half', 'Half')], default='monthly', max_length=25),
        ),
    ]
