# Generated by Django 5.1.4 on 2025-01-17 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('inspection', '0002_iosinspectresult_library_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidinspectresult',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='iosinspectresult',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
