# Generated by Django 5.1.4 on 2025-02-05 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_devices_unique_together'),
        ('inspection', '0004_alter_androidinspectresult_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='androidinspectresult',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='iosinspectresult',
            name='device_info',
        ),
        migrations.AddField(
            model_name='androidinspectresult',
            name='app_name',
            field=models.CharField(default='Unknown', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='androidinspectresult',
            name='app_version',
            field=models.CharField(default='Unknown', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='androidinspectresult',
            name='normal_device_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aos_normal_device', to='devices.devices'),
        ),
        migrations.AddField(
            model_name='androidinspectresult',
            name='rooting_device_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aos_rooting_device', to='devices.devices'),
        ),
        migrations.AddField(
            model_name='iosinspectresult',
            name='app_name',
            field=models.CharField(default='Unknown', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='iosinspectresult',
            name='app_version',
            field=models.CharField(default='Unknown', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='iosinspectresult',
            name='normal_device_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ios_normal_device', to='devices.devices'),
        ),
        migrations.AddField(
            model_name='iosinspectresult',
            name='rooting_device_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ios_rooting_device', to='devices.devices'),
        ),
    ]
