# Generated by Django 5.1.4 on 2025-02-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_remove_androidinspectresult_device_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='androidinspectresult',
            name='normal_device_info',
        ),
        migrations.RemoveField(
            model_name='androidinspectresult',
            name='rooting_device_info',
        ),
        migrations.RemoveField(
            model_name='iosinspectresult',
            name='normal_device_info',
        ),
        migrations.RemoveField(
            model_name='iosinspectresult',
            name='rooting_device_info',
        ),
    ]
