# Generated by Django 5.1.4 on 2025-02-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_remove_androidinspectresult_device_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='androidinspectresult',
            name='normal_device_info',
        ),
        migrations.RemoveField(
            model_name='androidinspectresult',
            name='rooting_device_info',
        ),
        migrations.RemoveField(
            model_name='iosinspectresult',
            name='normal_device_info',
        ),
        migrations.RemoveField(
            model_name='iosinspectresult',
            name='rooting_device_info',
        ),
        migrations.AddField(
            model_name='androidinspectresult',
            name='inspection_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='androidinspectresult',
            name='significant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='iosinspectresult',
            name='inspection_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='iosinspectresult',
            name='significant',
            field=models.TextField(null=True),
        ),
    ]
