# Generated by Django 5.1.4 on 2025-02-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_remove_androidinspectresult_normal_device_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidinspectresult',
            name='inspection_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='iosinspectresult',
            name='inspection_date',
            field=models.DateField(null=True),
        ),
    ]
