# Generated by Django 5.1.4 on 2025-11-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_remove_androidinspectresult_normal_device_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionresultfile',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='inspectionresultfile',
            table='InspectionResultFile',
        ),
    ]
