# Generated by Django 5.1.4 on 2025-02-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_androidinspectresult_inspection_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidinspectresult',
            name='significant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='iosinspectresult',
            name='significant',
            field=models.TextField(null=True),
        ),
    ]
