# Generated by Django 5.1.4 on 2025-11-07 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_alter_inspectionresultfile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidObfuscateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obfuscate', models.TextField(default='Unknown', null=True)),
                ('momo_size', models.TextField(default='Unknown', null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.androidinspectresult')),
            ],
            options={
                'db_table': 'AndroidObfuscateResult',
                'managed': True,
            },
        ),
    ]
