# Generated by Django 5.1.4 on 2025-03-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
