# Generated by Django 5.1.4 on 2025-03-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_organization_alter_contactemail_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='contacts',
            field=models.ManyToManyField(related_name='labels', to='contact.organization'),
        ),
    ]
